//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Store.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [SpecialSetting(SpecialSetting.ConnectionString)]
        [DefaultSettingValue("Data Source=(LOCAL);Initial Catalog=POS;Persist Security Info=True;User ID=SA;Pas" +
            "sword=mutawa2011")]
        public string POSConnectionString {
            get {
                return ((string)(this["POSConnectionString"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [SpecialSetting(SpecialSetting.ConnectionString)]
        [DefaultSettingValue("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Users\\Arehman-lptp\\Desktop\\CPHMAS" +
            ".MDB")]
        public string CPHMASConnectionString {
            get {
                return ((string)(this["CPHMASConnectionString"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Data Source=78.93.190.90;Initial Catalog=POS;User ID=SA;Password=mutawa2011")]
        public string RemoteServer {
            get {
                return ((string)(this["RemoteServer"]));
            }
            set {
                this["RemoteServer"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Data Source=78.93.190.90;Initial Catalog=SYNC;User ID=SA;Password=mutawa2011")]
        public string RemoteSync {
            get {
                return ((string)(this["RemoteSync"]));
            }
            set {
                this["RemoteSync"] = value;
            }
        }
    }
}
